const state={jobs:[],filtered:[],visible:8};
const $=id=>document.getElementById(id);
const clean=value=>String(value??'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
const classify=job=>{const text=`${job.title} ${job.description}`.toLowerCase();if(/intern(ship)?/.test(text))return'Internship';if(/graduate|grad program|entry.level/.test(text))return'Graduate';if(/part[ -]?time/.test(text))return'Part-time';if(/casual|seasonal/.test(text))return'Casual';return job.type||'Other'};
const relative=date=>{const days=Math.max(0,Math.floor((Date.now()-new Date(date))/86400000));return days===0?'Today':days===1?'1 day ago':`${days} days ago`};
function render(){const box=$('jobs');box.replaceChildren();state.filtered.slice(0,state.visible).forEach(job=>{const node=$('jobTemplate').content.cloneNode(true);node.querySelector('.job-type').textContent=classify(job);node.querySelector('time').textContent=relative(job.created);node.querySelector('h3').textContent=clean(job.title);node.querySelector('.company').textContent=clean(job.company);node.querySelector('.location').textContent=clean(job.location)||'Australia';node.querySelector('.description').textContent=clean(job.description)||'Open the listing for full role details.';node.querySelector('a').href=job.url;box.append(node)});$('resultCount').textContent=`${state.filtered.length} job${state.filtered.length===1?'':'s'} found`;$('status').textContent=state.filtered.length?'':'No matching roles yet. Try broadening your search.';$('loadMore').hidden=state.visible>=state.filtered.length}
function filter(){const keyword=$('keyword').value.trim().toLowerCase(),location=$('location').value.trim().toLowerCase(),type=$('type').value;state.filtered=state.jobs.filter(j=>`${j.title} ${j.company} ${j.description}`.toLowerCase().includes(keyword)&&`${j.location}`.toLowerCase().includes(location)&&(!type||classify(j)===type));const sort=$('sort').value;state.filtered.sort((a,b)=>sort==='newest'?new Date(b.created)-new Date(a.created):String(a[sort]).localeCompare(String(b[sort])));state.visible=8;render()}
async function init(){try{const response=await fetch('data/jobs.json',{cache:'no-store'});if(!response.ok)throw new Error();state.jobs=await response.json();filter()}catch{$('resultCount').textContent='Jobs unavailable';$('status').textContent='We could not load listings right now. Please try again soon.'}}
$('searchButton').addEventListener('click',filter);$('sort').addEventListener('change',filter);$('type').addEventListener('change',filter);['keyword','location'].forEach(id=>$(id).addEventListener('keydown',e=>{if(e.key==='Enter')filter()}));$('loadMore').addEventListener('click',()=>{state.visible+=8;render()});$('year').textContent=new Date().getFullYear();init();
